import {Link} from 'react-router-dom'

export default function BlogPlan(){

    return(
        <>
            <h1 className="text-7xl text-center mt-6 mb-3 font-['hey-november']">How We're Achieving Our Plans (Operationally)</h1>
            <p className="text-center text-xl tracking-[0.6rem] mb-4">BY: AIDAN TANG | JUNE 22, 2024 | 5 MINUTE READ</p>
            <div className="w-[55%] h-1 bg-white m-auto mb-6"></div>
            <div className="w-4/12 h-96 bg-[url('/src/assets/blog-plan-thumbnail.jpg')] bg-center bg-cover m-auto brightness-110 mb-6"/>

            
            <p className="mb-6 w-3/5 text-center m-auto">Last week, we described to you our plans for the future and what we intend to achieve. But there’s a difference between a dream and a goal, and at Urban Artisans, we are here to not just dream, but to execute that dream. In order to achieve our goals, we have developed three smaller objectives to fulfill first.</p>
            <p className="mb-6 w-3/5 text-center m-auto">First and foremost, we want to increase our overall brand recognition and consolidate a loyal and unique community (or customer demographic), as this would increase the chances of success for each location. Secondly, we would like to promote the sales of our unique, designer cups to a worldwide scale, feeding into the first goal we’ve devised, bringing more brand recognition as well as further generating a distinctive identity for our brand. Lastly, we would like to research what items are most effective through market research as well as our own experimentation in offerings, and double down on these flagship items to further grow our own unique identity and develop a relevant and effective menu. Overall, our objectives aim to further branch out our brand and make a name for ourselves within this fierce industry, something only possible through the global flexbiility of our designer cups, which are not restrained to physical locations. By strengthening our identity, it will be much easier to rapidly expand in the future, both digitally and physically. </p>
            <p className="mb-6 w-3/5 text-center m-auto">In order to achieve said objectives, we have devised a few projects and plans that we can use to achieve said objectives, which will in turn aid us in fulfilling our goal. Here are our current projects, subject to change:</p>
            <p className="mb-6 w-3/5 text-center m-auto">Develop a substantial social media presence in major sites like Twitter (or “X”), Instagram, and YouTube. Using these accounts, develop a reputation for being a trendy, innovative coffee company for the working, aspiring young adult that supports its communities. This can be done using posts highlighting community initiatives, YouTube videos promoting new cup designs and coffees, or even videos where the artists of said cups explain their thought process behind their work. </p>
            <p className="mb-6 w-3/5 text-center m-auto">Launch a large marketing campaign across North America for (or just Canada and the US) over the second series of our artistic designer cups. Of course, this comes with the ability to ship all across these two countries with some exceptions to a few territories and states (like Yukon or Alaska). First and foremost, we will likely require the services of a third-party retailer, like Amazon, to enable global delivery. To advertise and develop these cups, we will likely require a Product Development Manager / Officer. We might use major marketing sites like Times Square.</p>
            <p className="mb-6 w-3/5 text-center m-auto">Utilize surveys and review item popularities to determine what does and does not work for the coffee shop. Using this info, develop at least two large promotions in the span of a year surrounding a new, exclusive drink and observe public reception. To do this goal, we will likely utilize the work of nutritionists, food scientists, and the like. We might also use the services of a platform like Google Sites to retrieve data from our customers. </p>
            <p className="mb-6 w-3/5 text-center m-auto">Of course, these plans, although developed very thoroughly by our team, are not fool-proof. There are quite a few risks that come with our plan. For example, much of this plan is reliant on effective marketing, with each project incorporating marketing one way or another. Due to this, we have to carefully consider our marketing choices and make sure we use the most effective marketing outlets at our disposal. Another possible point of concern is that we are running two intense operations in two different markets, coffee and reusable cups, at once, which can lead to massive disarray if not handled properly. As such, we must always be collected and focused, responding to changes and competition in both markets, and respond effectively and efficiently. While there is quite a bit of risk to our plan, we are certain that it will come to fruition, as it's spearheaded by the finest and most creative of baristas, designers, and other creatives the world has to offer, all under one community: Urban Artisans.</p>

            <Link to="/blog"><button className="block m-auto border-white border-solid border-2 py-1 w-2/5 transition-all hover:bg-white rounded-lg hover:text-black mb-12 text-2xl tracking-[0.8rem]">BACK TO BLOG</button></Link>
        </>
    )

}