import {Link} from 'react-router-dom'

export default function BlogFunctions(){
    window.scrollTo(0,0)

    return(
        <>
            <h1 className="text-7xl text-center mt-6 mb-3 font-['hey-november']">The Four Management Functions & Us</h1>
            <p className="text-center text-xl tracking-[0.6rem] mb-4">BY: AIDAN TANG | JUNE 23, 2024 | 8 MINUTE READ</p>
            <div className="w-[55%] h-1 bg-white m-auto mb-6"></div>
            <div className="w-4/12 h-96 bg-[url('/src/assets/blog-leadership.jpg')] bg-center bg-cover m-auto brightness-110 mb-6"/>

            <p className="mb-6 w-3/5 text-center m-auto">At Urban Artisans, we believe communication through all parties is incredibly crucial, and as such, today, we want to discuss how we want Urban Artisans to be led through the four management functions: leading, planning, controlling, and planning.</p>
            <p className="mb-6 w-3/5 text-center m-auto">First and foremost would be the process of planning. To start, a core belief we hold is that we’re more productive when we know what we’re working towards, and as such, we always want to have a clear-cut envisionment of our future. Hence, we frequently develop goals at the Strategic level (multiple years) for everyone to collectively collaborate on. However, we want to also develop a roadmap towards our plans, and as such, we employ objectives as well. These objectives are small tasks that build up to our Strategic goal, and we aim to provide a clear roadmap for our plans with these as well as foster a sense of community and collaboration.</p>
            <p className="mb-6 w-3/5 text-center m-auto">We also would like to summarize our strategic goals, as well as overall mission without organization with our vision statement. Currently our vision statement is:</p>
            <p className="mb-6 w-3/5 text-center m-auto">“Urban Artisans is a global brand dedicated to innovating the world through its constantly evolving menu of both classic coffee beverages and experimental exclusives, its artistic designer cups, and its emphasis on social responsibility initiatives, invoking empowerment to both the youth and the underrepresented, our core demographic. We aim to be a brand that provides a personalized experience to each and every patron, employee, or otherwise through our diversity, as well as a sense of belonging and community as well through a productive and positive environment.”</p>
            <p className="mb-6 w-3/5 text-center m-auto">Next would be the process of organizing, which involves distributing resources efficiently and effectively to where they’re most needed. While we do value the equality provided by horizontal organization, we believe that the structure and organization  provided by a more traditional, vertical organization may be more beneficial, although we will definitely try to include each and every component of our hierarchy in our decision-making process, which will be meticulous and aware of all circumstances, both within and outside our organization. In summary, we want to make sure that what we need is delegated to those that are best suited for the job. </p>
            <p className="mb-6 w-3/5 text-center m-auto">The next management function we will be discussing is controlling, which is the process of evaluating where the business is at with its current goals, and altering its strategy to fit our current progress. At Urban Artisans, we always believe that improvement is always possible, and as such, we would like to use processes like Exit Interviews to evaluate our shortcomings and possible criticisms. In addition, we want to make sure everyone is always on the same page, and as such, we want to place great efforts in making sure the orientation process of new employees is concise but detailed and informative as well. </p>
            <p className="mb-6 w-3/5 text-center m-auto">Last comes leading. At Urban Artisans, we believe a good team is a team completely aligned on a certain vision, and as such, for the time being, we would like to remain a Limited Liability Company. We believe that stockholders may detract us from what we envision, and separate the connectivity we wish to have in all portions of our establishments. Moving on to our internal management, it is our envisionment that each store is handled with a laissez-faire model. We believe that this model of leadership is the most effective as different locations have different requirements and hurdles to overcome, and as such, each store opening shouldn’t just be streamlined. We want to foster a community that primarily fits the residents of said area, not just our own values. However, we still would like to maintain some kind of standard within each and every store, and as such, we’ve taken rigorous steps to make sure the process of being a manager leads to a dedicated and passionate leadership that upholds what we value most, and the adaptability that is required for the job. </p>
            <p className="mb-6 w-3/5 text-center m-auto">To conclude, that is how we want to execute the four management functions. We believe that this model is what’s best for our organization, but of course, we believe that change can be a force for the better. For a more in-depth view on our ideologies correlating with the four management functions, please view the following presentation below.</p>
             
            <a href="https://docs.google.com/presentation/d/e/2PACX-1vRsB7TwNtCEdOehGT0Bf74r1Hfr78V7fiXwJSoefYNbgnhFLwBwEsudUCFS4YOIm_Qamho5nOXw4q2L/pub?start=false&loop=false&delayms=3000" target="_blank"> <button className="block m-auto border-white border-solid border-2 py-1 w-2/5 transition-all hover:bg-white rounded-lg hover:text-black mb-12 text-2xl tracking-[0.8rem]">VIEW THE FULL PRESENTATION</button></a>
            <Link to="/blog"><button className="block m-auto border-white border-solid border-2 py-1 w-2/5 transition-all hover:bg-white rounded-lg hover:text-black mb-12 text-2xl tracking-[0.8rem]">BACK TO BLOG</button></Link>
        </>
    )

}