export default function About(){
    window.scrollTo(0,0)
    return(
        <>
            <h1 className="mt-4 font-['abuget'] text-[9rem] m-auto text-center leading-[1.1]">The Story Of Urban Artisans</h1>
            <p className="tracking-[0.4rem] m-auto text-center text-xl mb-6">OUR HISTORY, WHAT WE ARE, AND THE FUTURE</p>
            <div className="h-1 max-w-[18rem] bg-white m-auto mb-10"/>
            <p className="max-w-[70%] text-center m-auto mb-6">In the hustle and bustle of modern life, through the towering skyscrapers and the ambience from commuters of all kinds, we felt there was something missing. A second home, or perhaps a sense of community. Thus, the idea of Urban Artisans was born. A place where individuals could gather and express who they were - hobbies, interests, and the like, all the while enjoying bonding with each other over some fine hand-crafted coffee. This principle of expression was what inspired us to develop what is today our signature, artistic designer cups, as well as our experimental coffee flavors.</p>
            <p className="max-w-[70%] text-center m-auto mb-6">However, we want to do more than just be a humble abode for all; we want to change the world for the better, whether it be through experimenting for the next best tastes, or through our social responsibility initiatives empowering both the underrepresented and the youth to make their mark on our world. At heart, we believe that when we’re all aligned on the same goal, great things are imminent. This is what defines Urban Artisans, and empowerment will always come first.</p>

            <h1 className="text-2xl mt-12 text-center tracking-[0.4rem] mb-3">HUMBLE BEGINNINGS</h1>
            <div className="h-[0.05rem] w-[3rem] bg-white m-auto mb-6"/>
            <p className="max-w-[70%] text-center m-auto mb-6">Like most fledgling ideas in the world, the first priority was getting a catchy name that just rolled off the tongue. We experimented with countless combinations, whether that be the Urban Brewery, Artisan's Workshop, of The Artist’s Republic. However, as history would show, we eventually settled on the name: Urban Artisans. It had that sweet roll-off-the-tongue pronunciation that we were looking for, and we believe it perfectly describes the atmosphere we’re cultivating for in each and every one of our locations. It also didn’t lead to an acronym of TAR, which needless to say, isn’t exactly very appetizing. </p>
            <p className="max-w-[70%] text-center m-auto mb-6">Next came our offerings. We didn’t just want to be the average run-off-the-mill kind of coffee shop. We wanted to bring new flavors to town; give people the refreshing novelty we believe the coffee industry has been lacking recently. As such, we traveled all across the world, from Columbia to Vietnam, in search of the finest underdog pastries and drinks. In the end, we crafted what we believed to be a fine menu, containing comforting staples like the espresso and chewy chocolate chip cookies, combining that with an emphasis on lesser-known variants of coffee like the Cold Brew, all to top it off with some homemade exclusives like our “Boba Coffee”, fusing the best of Southeast Asian bubble tea with the classic taste of coffee. No matter what your taste buds might be craving, we have something right up your alley. </p>
            <p className="max-w-[70%] text-center m-auto mb-6">With our freshly-developed idea in mind, we would eventually open our first two stores in Toronto, Ontario. To us, this isn’t the end, but rather the beginning of what we hope to be a positive force on our planet. This is Urban Artisans, and we’ll continue to strive for greater. No matter who you are, whether that be race, sexuality, or gender, come join our communities, whether it be on social media or in person! We will always welcome you in our doors!</p>
        </>
    )
}